# Generated by Django 6.0.5 on 2026-06-30 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('socio', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('capacidade', models.PositiveIntegerField(default=0)),
                ('valor_socio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_nao_socio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caucao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('foto_capa', models.ImageField(blank=True, null=True, upload_to='espacos/capas/')),
                ('churrasqueira', models.BooleanField(default=False)),
                ('cozinha', models.BooleanField(default=False)),
                ('freezer', models.BooleanField(default=False)),
                ('geladeira', models.BooleanField(default=False)),
                ('ar_condicionado', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('estacionamento', models.BooleanField(default=False)),
                ('banheiros', models.BooleanField(default=False)),
                ('regras', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em manutenção'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoEspaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='espacos/galeria/')),
                ('legenda', models.CharField(blank=True, max_length=150)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='reservas.espaco')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('quantidade_pessoas', models.PositiveIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('whatsapp', 'WhatsApp')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando confirmação'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.cliente')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.espaco')),
            ],
        ),
    ]
