# Generated by Django 6.0.5 on 2026-07-02 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='espaco',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='fotoespaco',
            options={'ordering': ['ordem', 'id']},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-data', '-hora_inicio']},
        ),
        migrations.AddField(
            model_name='fotoespaco',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fotoespaco',
            name='ordem',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
