# Generated by Django 6.0.5 on 2026-07-02 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_cliente_options_alter_espaco_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espaco',
            name='valor_nao_socio',
        ),
    ]
