# Generated by Django 6.0.5 on 2026-07-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_espaco_valor_nao_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='aceitou_regras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='brinquedos_inflaveis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='churrasqueira_rotativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='decoracao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='musica_ao_vivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='periodo',
            field=models.CharField(blank=True, choices=[('meio_dia', 'Meio-dia'), ('tarde', 'Tarde'), ('noite', 'Noite')], default='noite', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_utensilios',
            field=models.CharField(blank=True, choices=[('', 'Não informado'), ('mesas', 'Já deixar montado nas mesas'), ('buffet', 'Deixar tudo em uma mesa - sistema buffet')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='toalhas',
            field=models.CharField(blank=True, choices=[('', 'Não informado'), ('tnt', 'TNT brancas sem custo'), ('tecido', 'Tecido brancas + R$ 60,00 extra')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='utensilios_vidro',
            field=models.BooleanField(default=False),
        ),
    ]
