# Generated by Django 6.0.5 on 2026-07-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_aceitou_regras_reserva_brinquedos_inflaveis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_boas_vindas', models.TextField(default='👋 Olá! Bem-vindo à Associação Balneária Panambi.')),
                ('mensagem_confirmacao', models.TextField(default='✅ Sua solicitação foi registrada com sucesso.')),
                ('mensagem_sem_disponibilidade', models.TextField(default='❌ Não há disponibilidade para esta data.')),
                ('mensagem_atendente', models.TextField(default='👩\u200d💼 Sua conversa será encaminhada para a secretaria. Aguarde atendimento.')),
                ('contato_secretaria', models.CharField(blank=True, max_length=120)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do WhatsApp',
                'verbose_name_plural': 'Configurações do WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='RegraReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('texto', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativa', models.BooleanField(default=True)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regra da Reserva',
                'verbose_name_plural': 'Regras da Reserva',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='espaco',
            options={'ordering': ['nome'], 'verbose_name': 'Espaço', 'verbose_name_plural': 'Espaços'},
        ),
        migrations.AlterModelOptions(
            name='fotoespaco',
            options={'ordering': ['ordem', 'id'], 'verbose_name': 'Foto do Espaço', 'verbose_name_plural': 'Fotos dos Espaços'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-data', '-hora_inicio'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
